spring.application.name=Practica

# Usamos la IP o el nombre del servicio si estás en Docker
spring.datasource.url=jdbc:mysql://localhost:3307/mysql-server?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

# Cambiamos a la versión moderna del Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080